name: go_router_aggregator_example
description: "An example project for go_router_aggregator package"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  go_router_builder: ^4.0.1
  go_router_aggregator: ^2.0.0

flutter:
  uses-material-design: true

# This is for the example to compile with the local version of the plugin.
# You do not need to include this in your project.
dependency_overrides:
  go_router_aggregator:
    path: ../.
